#### In Class Assignment 12/04/23
#### Names: Debajyoti Naha, Aaron Vo, and Michael McCluskey
<br>Goal: Classify randomly generated binary data
<br>Gist: Speed development (35min); 
<br>1. Create a dataframe of randomly generated binary data, with 500 rows (user) x 50 columns (features) (‘col1’, ‘col2’, …) using at least two different distributions
<br>2. Create a NN to classify the 50th column of a new user (the 501st row)
<br>3. Your model will be bad. Why exactly will it be bad?
<br>4. What should your look like given that you know what data you just gave it?

In [1]:
import numpy as np
import pandas as pd

In [52]:
#Set Seed for Reproducibility
np.random.seed(123)

#Number of Rows and Columns
num_rows = 625
num_cols = 50
half_cols = int(num_cols / 2)

#Generate Dataset
binomial_columns = np.random.binomial(n=1, p=.5, size = (num_rows, half_cols))
normal_columns = np.random.normal(loc = 0.5, scale=0.2, size=(num_rows, half_cols))
normal_columns = np.where(normal_columns < 0.5, 0, 1)
full_data = np.concatenate([binomial_columns, normal_columns], axis=1)

#Column Names
col_names = [f'col{i+1}' for i in range(num_cols)]

#Create Dataframe
df_example = pd.DataFrame(full_data, columns = col_names)

In [53]:
df_example.head()

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col41,col42,col43,col44,col45,col46,col47,col48,col49,col50
0,1,0,0,1,1,0,1,1,0,0,...,1,1,1,0,0,1,0,1,1,0
1,0,0,0,0,1,0,0,0,0,0,...,1,1,0,0,1,0,1,1,0,0
2,0,1,1,1,0,0,0,1,1,1,...,0,0,1,1,1,0,1,1,1,0
3,1,1,0,0,1,0,1,1,0,1,...,0,0,0,1,0,1,0,0,0,1
4,1,1,0,0,0,1,1,1,1,0,...,0,1,1,0,0,1,0,1,1,0

In [63]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

#Split data into Train and Test
features = df_example.loc[:,'col1':'col49'].to_numpy()
target = df_example.loc[:,'col50'].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=100, test_size=0.2)

clf2 = MLPClassifier(activation = 'relu', solver='adam', alpha=1e-5,
                     hidden_layer_sizes=(20, 2), random_state=1, max_iter = 500)
clf2.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(20, 2), max_iter=50000,
              random_state=1)

In [64]:
predictions = clf2.predict(X_test)

print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.53      0.61      0.57        64
           1       0.52      0.44      0.48        61

    accuracy                           0.53       125
   macro avg       0.53      0.53      0.52       125
weighted avg       0.53      0.53      0.52       125